import type {CheatSection} from './cheatsheetContent';

export const CHEAT_SECTIONS: CheatSection[] = [
  {
    icon: '📦',
    title: 'Variables',
    cards: [
      {title: 'Affecter et lire', code: 'x = 5\nx = x + 1   # 6\nprint(x)    # 6',
       note: '= range une valeur sous un nom. Réaffecter ne fait que pointer le nom vers la nouvelle valeur.'},
      {title: 'Règles de nommage', code: 'score = 10      # snake_case ✅\nage_2 = 3       # digits ok after first char\nage 2 = 3       # ❌ space & leading digit\nScore = 10      # works, but remember: case-sensitive',
       note: 'Les noms sont sensibles à la casse. Utilisez snake_case, des noms descriptifs, et évitez les mots réservés comme print.'},
      {title: 'Échange et décomposition', code: 'a, b = 1, 2\na, b = b, a   # swap in one line\nfirst, *rest = [1, 2, 3]  # first=1, rest=[2, 3]',
       note: 'Python affecte plusieurs noms à la fois — le plus propre des échanges.'},
    ],
  },
  {
    icon: '🖨️',
    title: 'Sortie',
    cards: [
      {title: 'print', code: "print('Hello, world!')\nprint(2 + 3)      # 5, values print automatically",
       note: 'La seule fonction que vous utiliserez à chaque leçon.'},
      {title: 'Séparateur', code: "print('a', 'b', sep='-')   # a-b",
       note: 'sep contrôle le séparateur ; par défaut, c’est une espace.'},
    ],
  },
  {
    icon: '⌨️',
    title: 'Entrée',
    cards: [
      {title: 'Lire l’invite', code: "name = input('Your name: ')\nprint('Hi', name)",
       note: 'input() fait une pause et attend ; elle renvoie TOUJOURS une chaîne.'},
      {title: 'Convertir', code: "age = int(input('Age: '))\nprice = float(input('Price: '))",
       note: 'Convertissez à la lecture avec int()/float(), sinon chaque étape de calcul échouera ensuite.'},
    ],
  },
  {
    icon: '🔢',
    title: 'Nombres',
    cards: [
      {title: 'Arithmétique de base', code: 'x = 7\nx // 2   # 3  integer division\nx % 2    # 1  remainder\nx ** 2   # 49 exponent',
       note: '// et % forment un duo — ils répondent « combien de fois » et « combien reste-t-il ».',},
      {title: 'type()', code: 'type(3)     # <class \'int\'>\ntype(3.0)   # <class \'float\'>\ntype("3")   # <class \'str\'>',
       note: 'Vérifiez le type de n’importe quelle valeur quand une erreur évoque un décalage de type.'},
      {title: 'Conversion', code: "int('42')   # 42\nfloat('4.2')\nstr(42)     # '42'",
       note: 'input() renvoie toujours une chaîne — convertissez avant de faire des calculs.'},
    ],
  },
  {
    icon: '📝',
    title: 'Chaînes',
    cards: [
      {title: 'f-strings', code: "name = 'PyDA'\nprint(f'{name} → {len(name)} letters')",
       note: 'Le f avant le guillemet fait insérer les valeurs des {…}. Utilisez ça, pas la concaténation.'},
      {title: 'Méthodes', code: "'  hi  '.strip()   # 'hi'\n'hello'.upper()   # 'HELLO'\n'a,b'.split(',')   # ['a', 'b']",
       note: 'Les méthodes renvoient une NOUVELLE chaîne — les chaînes sont immuables.'},
      {title: 'Découpage', code: "word = 'python'\nword[0]    # 'p'\nword[-1]   # 'n'\nword[1:4]  # 'yth'",
       note: 'Le début est inclus, la fin exclue. Les index négatifs comptent depuis la fin.'},
      {title: 'Combiner, répéter, chercher', code: "'py' + 'thon'    # 'python'\n'ha' * 3        # 'hahaha'\n'py' in 'python'  # True\nlen('abc')        # 3",
       note: '+ colle les chaînes, * les répète, in teste la présence d’une sous-chaîne, len() compte les caractères.'},
      {title: 'Échappements antislash', code: "print('she\\'s fine')   # she's fine\nprint('line1\\nline2')  # two lines\nprint('tab\\there')      # tab       here",
       note: "\\' est un guillemet, \\n un saut de ligne, \\t une tabulation. Utilisez les chaînes brutes r\"…\" quand un chemin contient trop d’antislashs."},
    ],
  },
  {
    icon: '📚',
    title: 'Listes',
    cards: [
      {title: 'Construire et ajouter', code: 'nums = [1, 2, 3]\nnums.append(4)      # [1, 2, 3, 4]\nnums + [5]        # [1, 2, 3, 4, 5]',
       note: 'append modifie la liste sur place ; + en crée une nouvelle.'},
      {title: 'Lire', code: 'nums[0]      # 1\nlen(nums)    # 4\nnums[-1]     # 4\n3 in nums    # True',
       note: 'in / not in sont les vérifications d’appartenance.'},
      {title: 'Parcourir', code: 'for n in nums:\n    print(n * 2)',
       note: 'La boucle for atteint chaque élément un par un.'},
      {title: 'Trier et copier', code: 'nums.sort()          # in place\nsorted(nums)         # NEW sorted list\ncopy = nums[:]       # real copy, not the same list',
       note: 'sort() modifie la liste et renvoie None ; sorted() renvoie une nouvelle. Utilisez nums[:] pour travailler sur une copie.'},
      {title: 'Astuces de découpage', code: 'nums = [0, 1, 2, 3, 4]\nnums[1:]    # [1, 2, 3, 4]  drop the head\nnums[:-1]   # [0, 1, 2, 3]  drop the tail\nnums[::-1]  # [4, 3, 2, 1, 0]  reversed',
       note: 'La forme [start:end:step] est la chirurgie des listes — supprimer, copier et inverser en une ligne.'},
    ],
  },
  {
    icon: '🏷️',
    title: 'Tuples et Ensembles',
    cards: [
      {title: 'Tuples', code: "t = (1, 2, 3)\nt[0]        # 1\nx, y = t        # unpack\n# t[0] = 9      # ❌ tuples can't change",
       note: 'Une liste figée — utilisez-la quand la forme ne doit pas changer : coordonnées, paires de config, données en lecture seule.'},
      {title: 'Ensembles', code: "s = {1, 2, 2, 3}   # {1, 2, 3} — duplicates dropped\ns.add(4)\n4 in s        # True\ns.remove(4)",
       note: 'Un sac non ordonné d’éléments uniques — idéal pour dédupliquer et pour des tests d’appartenance rapides.'},
      {title: 'Opérations d’ensembles', code: "a = {1, 2, 3}\nb = {3, 4}\na | b       # {1, 2, 3, 4}  union\na & b       # {3}           intersection\na - b       # {1, 2}        difference\na ^ b       # {1, 2, 4}     symmetric",
       note: '| , & , - , ^ transforment les ensembles en calcul en une ligne — comparez des groupes sans boucles imbriquées.'},
      {title: 'Quel conteneur ?', code: 'list    # ordered, editable, keeps order\ntuple   # ordered, read-only\nset     # unordered, unique, fast in\ndict    # key → value lookup',
       note: 'Choisissez selon ce dont le code a besoin : l’ordre, l’unicité, ou retrouver des choses par leur nom.'},
    ],
  },
  {
    icon: '🗂️',
    title: 'Dictionnaires',
    cards: [
      {title: 'Construire et lire', code: "ages = {'ada': 36, 'bob': 41}\nages['ada']        # 36\nages.get('zoe')    # None (safe \"missing\")\nages.get('zoe', 0) # 0 (with default)",
       note: 'Utiliser [key] sur une clé absente lève KeyError — préférez .get() quand vous n’êtes pas sûr.'},
      {title: 'Écrire', code: "ages['ada'] = 37\nages['zoe'] = 22\ndel ages['bob']",
       note: 'L’affectation ajoute ou met à jour ; del supprime une clé.'},
      {title: 'Itérer', code: "for k, v in ages.items():\n    print(k, v)",
       note: '.items() donne des paires (clé, valeur) ; .keys() et .values() n’en donnent qu’un côté.'},
    ],
  },
  {
    icon: '🔀',
    title: 'Conditionnelles',
    cards: [
      {title: 'if / elif / else', code: 'if score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")',
       note: 'elif s’arrête dès qu’une condition est vraie — l’ordre compte.'},
      {title: 'Comparaisons', code: '==  !=  <  <=  >  >=',
       note: '== teste l’égalité ; = affecte. S’en souvenir corrige la plupart des bugs « pourquoi c’est True ».'},
      {title: 'Opérateurs booléens', code: 'a and b    # both truthy\na or b     # at least one\na and not b',
       note: 'and / or / not — les mots simples, pas && ni ! comme dans d’autres langages.'},
      {title: 'Véracité', code: "if x:             # 'is x non-empty?'\n    print(x)\n# Falsy: 0, 0.0, '', [], {}, None\n# Everything else is truthy",
       note: '« if x: » est le « est-ce que x est là ? » idiomatique — les conteneurs vides et 0 échouent, tout le reste passe.'},
      {title: 'Ternaire en une ligne', code: "'pass' if score >= 50 else 'fail'",
       note: 'Un if/else compact qui renvoie une valeur — pratique dans les f-strings et print().'},
    ],
  },
  {
    icon: '🔁',
    title: 'Boucles',
    cards: [
      {title: 'range', code: 'for i in range(3):   # 0, 1, 2\n    print(i)\nfor i in range(1, 4): # 1, 2, 3\n    print(i)',
       note: 'range s’arrête avant le second nombre — même règle d’exclusion de fin que le découpage.'},
      {title: 'enumerate / zip', code: "for i, item in enumerate(['a','b']):\n    print(i, item)\nfor x, y in zip([1,2],[3,4]):\n    print(x, y)",
       note: 'enumerate ajoute un compteur ; zip associe deux séquences élément par élément.'},
      {title: 'break / continue', code: 'for n in range(10):\n    if n == 3:\n        break      # stop the loop\nfor n in range(10):\n    if n % 2:\n        continue   # skip this one\n    print(n)',
       note: 'break quitte la boucle entièrement ; continue passe à l’itération suivante.'},
      {title: 'while', code: 'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1   # don\'t forget: while needs progress',
       note: 'while répète jusqu’à ce que sa condition devienne fausse — une boucle qui ne met jamais à jour sa condition ne finit jamais.'},
      {title: 'else de boucle (optionnel)', code: 'for n in nums:\n    if n == target:\n        break\nelse:\n    print("not found")',
       note: 'Le bloc else ne s’exécute que si la boucle s’est terminée sans break — un indicateur intégré « a-t-on trouvé ? ».'},
    ],
  },
  {
    icon: '🛠️',
    title: 'Fonctions',
    cards: [
      {title: 'Définir et appeler', code: 'def double(x):\n    return x * 2\n\ny = double(21)   # 42',
       note: 'Le corps de def … doit être indenté. return redonne une valeur ; sans lui vous obtenez None.'},
      {title: 'Valeurs par défaut et mots-clés', code: 'def greet(name, exclaim=True):\n    s = f"Hello {name}"\n    return s + ("!" if exclaim else "")\n\ngreet("ada")        # Hello ada!\ngreet("ada", False) # Hello ada',
       note: 'Les paramètres avec = ont des valeurs par défaut ; les appelants peuvent passer par mot-clé.'},
      {title: 'Renvoyer plusieurs valeurs', code: 'def minmax(nums):\n    return min(nums), max(nums)\n\nlo, hi = minmax([3, 1, 4])  # lo=1, hi=4',
       note: 'Une fonction peut renvoyer un tuple que les appelants décomposent en plusieurs noms d’un coup.'},
      {title: 'Portée et print vs return', code: 'x = 10            # global\n\ndef show(y):\n    x = 5         # local — different x!\n    print(x, y)   # side effect, returns None\n\nresult = show(1)  # result is None',
       note: 'print affiche une valeur dans la console ; return la rend vraiment. Affecter dans une fonction masque la variable globale.'},
      {title: 'Lambda (formes courtes)', code: 'double = lambda x: x * 2\nsorted(nums, key=lambda n: -n)',
       note: 'Utilisez les lambdas pour des fonctions jetables d’une ligne passées à sort/max/map.'},
    ],
  },
  {
    icon: '🧰',
    title: 'Compréhensions',
    cards: [
      {title: 'Liste', code: '[n * 2 for n in nums]              # [2, 4, 6]\n[n for n in nums if n > 1]      # [2, 3]\n{n * 2 for n in nums}           # set',
       note: 'Une boucle for entre crochets — la façon idiomatique de transformer une liste.'},
      {title: 'Dict', code: "{n: n ** 2 for n in range(4)}   # {0: 0, 1: 1, 2: 4, 3: 9}",
       note: 'Même forme, avec deux-points entre la clé et la valeur.'},
    ],
  },
  {
    icon: '🗃️',
    title: 'Fichiers et CSV',
    cards: [
      {title: 'Lire un fichier', code: 'text = open("file.txt").read()\nlines = text.splitlines()',
       note: 'La lecture la plus simple ; utilisez with open(...) as f quand il faut un flux.'},
      {title: 'Lignes CSV', code: "import csv\nwith open('data.csv') as f:\n    rows = list(csv.reader(f))",
       note: 'rows[0] est l’en-tête ; chaque ligne suivante est une liste de chaînes — convertissez en nombres avant les calculs.'},
    ],
  },
  {
    icon: '🐼',
    title: 'pandas (Analyse de données)',
    cards: [
      {title: 'Charger et survoler', code: "import pandas as pd\ndf = pd.read_csv('data.csv')\ndf.head()      # first 5 rows\ndf.describe()  # numeric summary",
       note: 'L’incantation standard — pd.read_csv est la façon dont commence chaque leçon de données.'},
      {title: 'Colonnes et lignes', code: "df['name']          # one column\ndf[['a', 'b']]      # several\ndf.loc[0]           # first row\ndf[df['age'] > 30]  # filter rows",
       note: 'Des crochets sur un nom de colonne ; des masques booléens pour filtrer.'},
      {title: 'Regrouper et agréger', code: "df.groupby('city')['sales'].sum()\ndf.groupby('city').mean()",
       note: 'groupby + une méthode de synthèse est le pivot de la section Analyse de données.'},
    ],
  },
  {
    icon: '🛟',
    title: 'Récupération d’erreurs',
    cards: [
      {title: 'Lire la dernière ligne', code: "TypeError: unsupported operand type(s) for +: 'int' and 'str'",
       note: 'La dernière ligne nomme l’erreur et les valeurs fautives — c’est le message qui dit quoi corriger.'},
      {title: 'try / except', code: "try:\n    total = int(user_input) * 2\nexcept ValueError:\n    print('That was not a number')",
       note: 'Attrapez uniquement l’erreur précise attendue ; tout attraper masque de vrais bugs.'},
    ],
  },
];
