import type {CheatSection} from './cheatsheetContent';

export const CHEAT_SECTIONS: CheatSection[] = [
  {
    icon: '📦',
    title: 'Variables',
    cards: [
      {title: 'Asignar y leer', code: 'x = 5\nx = x + 1   # 6\nprint(x)    # 6',
       note: '= guarda un valor bajo un nombre. Reasignar solo apunta el nombre al nuevo valor.'},
      {title: 'Reglas de nombres', code: 'score = 10      # snake_case ✅\nage_2 = 3       # digits ok after first char\nage 2 = 3       # ❌ space & leading digit\nScore = 10      # works, but remember: case-sensitive',
       note: 'Los nombres distinguen mayúsculas de minúsculas. Usa snake_case, nombres descriptivos y evita palabras propias como print.'},
      {title: 'Intercambiar y desempaquetar', code: 'a, b = 1, 2\na, b = b, a   # swap in one line\nfirst, *rest = [1, 2, 3]  # first=1, rest=[2, 3]',
       note: 'Python asigna varios nombres a la vez, el intercambio más limpio que existe.'},
    ],
  },
  {
    icon: '🖨️',
    title: 'Salida',
    cards: [
      {title: 'print', code: "print('Hello, world!')\nprint(2 + 3)      # 5, values print automatically",
       note: 'La única función que usarás en todas las lecciones.'},
      {title: 'Sin coma final', code: "print('a', 'b', sep='-')   # a-b",
       note: 'sep controla el separador; el valor por defecto es un espacio.'},
    ],
  },
  {
    icon: '⌨️',
    title: 'Entrada',
    cards: [
      {title: 'Leer el mensaje', code: "name = input('Your name: ')\nprint('Hi', name)",
       note: 'input() se detiene y espera; SIEMPRE devuelve una cadena.'},
      {title: 'Convertirlo', code: "age = int(input('Age: '))\nprice = float(input('Price: '))",
       note: 'Convierte al leer con int()/float(), o fallará cada paso de matemáticas posterior.'},
    ],
  },
  {
    icon: '🔢',
    title: 'Números',
    cards: [
      {title: 'Aritmética básica', code: 'x = 7\nx // 2   # 3  integer division\nx % 2    # 1  remainder\nx ** 2   # 49 exponent',
       note: '// y % son los complementos de la división: responden "cuántas veces" y "cuánto queda".'},
      {title: 'type()', code: 'type(3)     # <class \'int\'>\ntype(3.0)   # <class \'float\'>\ntype("3")   # <class \'str\'>',
       note: 'Comprueba el tipo de cualquier valor cuando un error mencione un desajuste de tipos.'},
      {title: 'Convertir', code: "int('42')   # 42\nfloat('4.2')\nstr(42)     # '42'",
       note: 'input() siempre devuelve una cadena: conviértela antes de hacer matemáticas.'},
    ],
  },
  {
    icon: '📝',
    title: 'Cadenas',
    cards: [
      {title: 'f-strings', code: "name = 'PyDA'\nprint(f'{name} → {len(name)} letters')",
       note: 'La f antes de la comilla hace que {…} inserte valores. Úsalas, no la concatenación.'},
      {title: 'Métodos', code: "'  hi  '.strip()   # 'hi'\n'hello'.upper()   # 'HELLO'\n'a,b'.split(',')   # ['a', 'b']",
       note: 'Los métodos devuelven una cadena NUEVA: las cadenas son inmutables.'},
      {title: 'Rebanar', code: "word = 'python'\nword[0]    # 'p'\nword[-1]   # 'n'\nword[1:4]  # 'yth'",
       note: 'El inicio es inclusivo, el final exclusivo. Los índices negativos cuentan desde el final.'},
      {title: 'Combinar, repetir, buscar', code: "'py' + 'thon'    # 'python'\n'ha' * 3        # 'hahaha'\n'py' in 'python'  # True\nlen('abc')        # 3",
       note: '+ une cadenas, * las repite, in comprueba una subcadena y len() cuenta caracteres.'},
      {title: 'Escape con barra invertida', code: "print('she\\'s fine')   # she's fine\nprint('line1\\nline2')  # two lines\nprint('tab\\there')      # tab       here",
       note: "\\' es una comilla, \\n una línea nueva y \\t una tabulación. Usa cadenas crudas r\"…\" cuando una ruta tenga demasiadas barras."},
    ],
  },
  {
    icon: '📚',
    title: 'Listas',
    cards: [
      {title: 'Crear y añadir', code: 'nums = [1, 2, 3]\nnums.append(4)      # [1, 2, 3, 4]\nnums + [5]        # [1, 2, 3, 4, 5]',
       note: 'append modifica la lista en su sitio; + crea una nueva.'},
      {title: 'Leer', code: 'nums[0]      # 1\nlen(nums)    # 4\nnums[-1]     # 4\n3 in nums    # True',
       note: 'in / not in son las comprobaciones de pertenencia.'},
      {title: 'Recorrer', code: 'for n in nums:\n    print(n * 2)',
       note: 'El bucle for alcanza cada elemento uno a la vez.'},
      {title: 'Ordenar y copiar', code: 'nums.sort()          # in place\nsorted(nums)         # NEW sorted list\ncopy = nums[:]       # real copy, not the same list',
       note: 'sort() cambia la lista y devuelve None; sorted() devuelve una nueva. Usa nums[:] para trabajar sobre una copia.'},
      {title: 'Trucos con rebanadas', code: 'nums = [0, 1, 2, 3, 4]\nnums[1:]    # [1, 2, 3, 4]  drop the head\nnums[:-1]   # [0, 1, 2, 3]  drop the tail\nnums[::-1]  # [4, 3, 2, 1, 0]  reversed',
       note: 'La forma [inicio:fin:paso] es cirugía de listas: eliminar, copiar e invertir en una línea.'},
    ],
  },
  {
    icon: '🏷️',
    title: 'Tuplas y Conjuntos',
    cards: [
      {title: 'Tuplas', code: "t = (1, 2, 3)\nt[0]        # 1\nx, y = t        # unpack\n# t[0] = 9      # ❌ tuples can't change",
       note: 'Una lista fija: úsala cuando la forma no deba cambiar: coordenadas, pares de configuración, datos de solo lectura.'},
      {title: 'Conjuntos', code: "s = {1, 2, 2, 3}   # {1, 2, 3} — duplicates dropped\ns.add(4)\n4 in s        # True\ns.remove(4)",
       note: 'Una bolsa sin orden de elementos únicos: perfecto para eliminar duplicados y comprobaciones de pertenencia rápidas.'},
      {title: 'Operaciones de conjuntos', code: "a = {1, 2, 3}\nb = {3, 4}\na | b       # {1, 2, 3, 4}  union\na & b       # {3}           intersection\na - b       # {1, 2}        difference\na ^ b       # {1, 2, 4}     symmetric",
       note: '|, &, -, ^ convierten los conjuntos en matemáticas de una línea: compara grupos sin bucles anidados.'},
      {title: '¿Qué contenedor?', code: 'list    # ordered, editable, keeps order\ntuple   # ordered, read-only\nset     # unordered, unique, fast in\ndict    # key → value lookup',
       note: 'Elige según lo que necesite el código: orden, unicidad o encontrar cosas por nombre.'},
    ],
  },
  {
    icon: '🗂️',
    title: 'Diccionarios',
    cards: [
      {title: 'Crear y leer', code: "ages = {'ada': 36, 'bob': 41}\nages['ada']        # 36\nages.get('zoe')    # None (safe \"missing\")\nages.get('zoe', 0) # 0 (with default)",
       note: 'Usar [clave] con una clave inexistente lanza KeyError: prefiere .get() cuando dudes.'},
      {title: 'Escribir', code: "ages['ada'] = 37\nages['zoe'] = 22\ndel ages['bob']",
       note: 'Asignar añade o actualiza; del elimina una clave.'},
      {title: 'Iterar', code: "for k, v in ages.items():\n    print(k, v)",
       note: '.items() da pares (clave, valor); .keys() y .values() dan solo un lado.'},
    ],
  },
  {
    icon: '🔀',
    title: 'Condicionales',
    cards: [
      {title: 'if / elif / else', code: 'if score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")',
       note: 'elif se detiene en cuanto una condición es True: el orden importa.'},
      {title: 'Comparaciones', code: '==  !=  <  <=  >  >=',
       note: '== comprueba igualdad; = asigna. Recordarlo arregla la mayoría de errores de "por qué es True".'},
      {title: 'Operadores booleanos', code: 'a and b    # both truthy\na or b     # at least one\na and not b',
       note: 'and / or / not: las palabras simples, no && ni ! como en otros lenguajes.'},
      {title: 'Veracidad', code: "if x:             # 'is x non-empty?'\n    print(x)\n# Falsy: 0, 0.0, '', [], {}, None\n# Everything else is truthy",
       note: '"if x:" es la comprobación idiomática de "¿está x?"; los contenedores vacíos y el 0 fallan, todo lo demás pasa.'},
      {title: 'Ternario en una línea', code: "'pass' if score >= 50 else 'fail'",
       note: 'Un if/else compacto que devuelve un valor: estupendo dentro de f-strings y print().'},
    ],
  },
  {
    icon: '🔁',
    title: 'Bucles',
    cards: [
      {title: 'range', code: 'for i in range(3):   # 0, 1, 2\n    print(i)\nfor i in range(1, 4): # 1, 2, 3\n    print(i)',
       note: 'range se detiene antes del segundo número: la misma regla de extremo exclusivo que las rebanadas.'},
      {title: 'enumerate / zip', code: "for i, item in enumerate(['a','b']):\n    print(i, item)\nfor x, y in zip([1,2],[3,4]):\n    print(x, y)",
       note: 'enumerate añade un contador; zip empareja dos secuencias elemento a elemento.'},
      {title: 'break / continue', code: 'for n in range(10):\n    if n == 3:\n        break      # stop the loop\nfor n in range(10):\n    if n % 2:\n        continue   # skip this one\n    print(n)',
       note: 'break abandona el bucle por completo; continue salta a la siguiente iteración.'},
      {title: 'while', code: 'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1   # don\'t forget: while needs progress',
       note: 'while se repite hasta que su condición sea False: un bucle que nunca actualiza su condición nunca termina.'},
      {title: 'else del bucle (opcional)', code: 'for n in nums:\n    if n == target:\n        break\nelse:\n    print("not found")',
       note: 'El bloque else solo se ejecuta si el bucle terminó sin break: un indicador integrado de "¿se encontró?".'},
    ],
  },
  {
    icon: '🛠️',
    title: 'Funciones',
    cards: [
      {title: 'Definir y llamar', code: 'def double(x):\n    return x * 2\n\ny = double(21)   # 42',
       note: 'El cuerpo de def… debe estar indentado. return entrega un valor; sin él obtienes None.'},
      {title: 'Valores por defecto y palabras clave', code: 'def greet(name, exclaim=True):\n    s = f"Hello {name}"\n    return s + ("!" if exclaim else "")\n\ngreet("ada")        # Hello ada!\ngreet("ada", False) # Hello ada',
       note: 'Los parámetros con = reciben valores por defecto; quien llama puede pasarlos por palabra clave.'},
      {title: 'Devolver varios valores', code: 'def minmax(nums):\n    return min(nums), max(nums)\n\nlo, hi = minmax([3, 1, 4])  # lo=1, hi=4',
       note: 'Una función puede devolver una tupla y quien la llama la desempaqueta en varios nombres a la vez.'},
      {title: 'Ámbito y print vs return', code: 'x = 10            # global\n\ndef show(y):\n    x = 5         # local — different x!\n    print(x, y)   # side effect, returns None\n\nresult = show(1)  # result is None',
       note: 'print muestra un valor en la consola; return realmente lo entrega. Asignar dentro de una función eclipsa la global.'},
      {title: 'Lambda (formas cortas)', code: 'double = lambda x: x * 2\nsorted(nums, key=lambda n: -n)',
       note: 'Usa lambdas para funciones desechables de una línea pasadas a sort/max/map.'},
    ],
  },
  {
    icon: '🧰',
    title: 'Comprensiones',
    cards: [
      {title: 'Lista', code: '[n * 2 for n in nums]              # [2, 4, 6]\n[n for n in nums if n > 1]      # [2, 3]\n{n * 2 for n in nums}           # set',
       note: 'Un bucle for entre corchetes: la forma idiomática de transformar una lista.'},
      {title: 'Diccionario', code: "{n: n ** 2 for n in range(4)}   # {0: 0, 1: 1, 2: 4, 3: 9}",
       note: 'La misma forma, con dos puntos entre la clave y el valor.'},
    ],
  },
  {
    icon: '🗃️',
    title: 'Archivos y CSV',
    cards: [
      {title: 'Leer un archivo', code: 'text = open("file.txt").read()\nlines = text.splitlines()',
       note: 'La lectura más sencilla; usa with open(...) as f cuando necesites procesar por tramos.'},
      {title: 'Filas CSV', code: "import csv\nwith open('data.csv') as f:\n    rows = list(csv.reader(f))",
       note: 'rows[0] es la cabecera; cada fila siguiente es una lista de cadenas: conviértelas a números antes de calcular.'},
    ],
  },
  {
    icon: '🐼',
    title: 'pandas (Análisis de datos)',
    cards: [
      {title: 'Cargar y echar un vistazo', code: "import pandas as pd\ndf = pd.read_csv('data.csv')\ndf.head()      # first 5 rows\ndf.describe()  # numeric summary",
       note: 'La fórmula estándar: pd.read_csv es cómo empieza toda lección de datos.'},
      {title: 'Columnas y filas', code: "df['name']          # one column\ndf[['a', 'b']]      # several\ndf.loc[0]           # first row\ndf[df['age'] > 30]  # filter rows",
       note: 'Corchetes sobre un nombre de columna; máscaras booleanas para filtrar.'},
      {title: 'Agrupar y agregar', code: "df.groupby('city')['sales'].sum()\ndf.groupby('city').mean()",
       note: 'groupby más un método de resumen es el eje de la sección de Análisis de datos.'},
    ],
  },
  {
    icon: '🛟',
    title: 'Recuperación de errores',
    cards: [
      {title: 'Lee la última línea', code: "TypeError: unsupported operand type(s) for +: 'int' and 'str'",
       note: 'La última línea nombra el error y los valores ofensivos: es el mensaje que dice qué corregir.'},
      {title: 'try / except', code: "try:\n    total = int(user_input) * 2\nexcept ValueError:\n    print('That was not a number')",
       note: 'Captura solo el error concreto que esperas; capturarlo todo oculta errores reales.'},
    ],
  },
];
