import type {CheatSection} from './cheatsheetContent';

export const CHEAT_SECTIONS: CheatSection[] = [
  {
    icon: '📦',
    title: 'المتغيرات',
    cards: [
      {title: 'الإسناد والقراءة', code: 'x = 5\nx = x + 1   # 6\nprint(x)    # 6',
       note: 'علامة = تحفظ قيمة تحت اسمٍ ما. إعادة الإسناد تعيد ربط الاسم بالقيمة الجديدة فحسب.'},
      {title: 'قواعد التسمية', code: 'score = 10      # snake_case ✅\nage_2 = 3       # digits ok after first char\nage 2 = 3       # ❌ space & leading digit\nScore = 10      # works, but remember: case-sensitive',
       note: 'الأسماء حسّاسة لحالة الأحرف. استخدم snake_case وأسماءً وصفية وتجنّب الكلمات المدمجة مثل print.'},
      {title: 'التبديل والتفكيك', code: 'a, b = 1, 2\na, b = b, a   # swap in one line\nfirst, *rest = [1, 2, 3]  # first=1, rest=[2, 3]',
       note: 'تسنِد Python عدة أسماء دفعة واحدة — وهذا أسلوب التبديل الأفضل على الإطلاق.'},
    ],
  },
  {
    icon: '🖨️',
    title: 'الإخراج',
    cards: [
      {title: 'print', code: "print('Hello, world!')\nprint(2 + 3)      # 5, values print automatically",
       note: 'الدالة الوحيدة التي ستستخدمها في كل درس على الإطلاق.'},
      {title: 'بدون فاصلة زائدة', code: "print('a', 'b', sep='-')   # a-b",
       note: 'تتحكم sep في الفاصل؛ والافتراضي هو مسافة.'},
    ],
  },
  {
    icon: '⌨️',
    title: 'الإدخال',
    cards: [
      {title: 'قراءة المطالَب', code: "name = input('Your name: ')\nprint('Hi', name)",
       note: 'تتوقف input() وتنتظر؛ وهي تُرجع نصًّا دائمًا.'},
      {title: 'تحويل الناتج', code: "age = int(input('Age: '))\nprice = float(input('Price: '))",
       note: 'حوّل عند القراءة باستخدام int()/float()، وإلا فستفشل كل خطوة حسابية لاحقة.'},
    ],
  },
  {
    icon: '🔢',
    title: 'الأرقام',
    cards: [
      {title: 'العمليات الحسابية الأساسية', code: 'x = 7\nx // 2   # 3  integer division\nx % 2    # 1  remainder\nx ** 2   # 49 exponent',
       note: '// و % شريكان في القسمة — تجيبان عن «كم مرة» و«كم يتبقى».'},
      {title: 'type()', code: 'type(3)     # <class \'int\'>\ntype(3.0)   # <class \'float\'>\ntype("3")   # <class \'str\'>',
       note: 'افحص نوع أي قيمة عندما تذكر رسالة الخطأ عدم تطابق في الأنواع.'},
      {title: 'التحويل', code: "int('42')   # 42\nfloat('4.2')\nstr(42)     # '42'",
       note: 'تُرجع input() دائمًا نصًّا — حوّل قبل إجراء أي عملية حسابية.'},
    ],
  },
  {
    icon: '📝',
    title: 'النصوص',
    cards: [
      {title: 'f-string (تنسيق النصوص)', code: "name = 'PyDA'\nprint(f'{name} → {len(name)} letters')",
       note: 'الحرف f قبل علامة الاقتباس يجعل {…} تُدخِل القيم. استخدم هذا بدل الدمج بالـ +.'},
      {title: 'الأساليب (Methods)', code: "'  hi  '.strip()   # 'hi'\n'hello'.upper()   # 'HELLO'\n'a,b'.split(',')   # ['a', 'b']",
       note: 'الأساليب تُرجع نصًّا جديدًا — فالنصوص (السلاسل) غير قابلة للتعديل.'},
      {title: 'التقطيع', code: "word = 'python'\nword[0]    # 'p'\nword[-1]   # 'n'\nword[1:4]  # 'yth'",
       note: 'البداية شاملة والنهاية مستبعدة. المؤشرات السالبة تُعدّ من النهاية.'},
      {title: 'الدمج والتكرار والبحث', code: "'py' + 'thon'    # 'python'\n'ha' * 3        # 'hahaha'\n'py' in 'python'  # True\nlen('abc')        # 3",
       note: '+ تلصق النصوص، و* يكرّرها، و in يفحص نصًّا فرعيًّا، و len() تعدّ الأحرف.'},
      {title: 'الهروب بالشرطة المائلة الخلفية', code: "print('she\\'s fine')   # she's fine\nprint('line1\\nline2')  # two lines\nprint('tab\\there')      # tab       here",
       note: "\\' علامة اقتباس، و\\n سطر جديد، و\\t تبويب. استخدم النصوص الخام r\"…\" عندما يحتوي المسار على شرطات مائلة كثيرة."},
    ],
  },
  {
    icon: '📚',
    title: 'القوائم',
    cards: [
      {title: 'الإنشاء والإضافة', code: 'nums = [1, 2, 3]\nnums.append(4)      # [1, 2, 3, 4]\nnums + [5]        # [1, 2, 3, 4, 5]',
       note: 'append تعدّل القائمة في موضعها؛ بينما + تنشئ قائمة جديدة.'},
      {title: 'القراءة', code: 'nums[0]      # 1\nlen(nums)    # 4\nnums[-1]     # 4\n3 in nums    # True',
       note: 'in و not in هما معاملا فحص العضوية.'},
      {title: 'التكرار', code: 'for n in nums:\n    print(n * 2)',
       note: 'حلقة for تمرّ على كل عنصر واحدًا تلو الآخر.'},
      {title: 'الترتيب والنسخ', code: 'nums.sort()          # in place\nsorted(nums)         # NEW sorted list\ncopy = nums[:]       # real copy, not the same list',
       note: 'sort() تعدّل القائمة وتُعيد None؛ بينما sorted() تُعيد قائمة جديدة. استخدم nums[:] للعمل على نسخة.'},
      {title: 'حيل التقطيع', code: 'nums = [0, 1, 2, 3, 4]\nnums[1:]    # [1, 2, 3, 4]  drop the head\nnums[:-1]   # [0, 1, 2, 3]  drop the tail\nnums[::-1]  # [4, 3, 2, 1, 0]  reversed',
       note: 'صيغة [start:end:step] هي جراحة القوائم — حذف ونسخ وعكس في سطر واحد.'},
    ],
  },
  {
    icon: '🏷️',
    title: 'الصفوف والمجموعات',
    cards: [
      {title: 'الصفوف (Tuples)', code: "t = (1, 2, 3)\nt[0]        # 1\nx, y = t        # unpack\n# t[0] = 9      # ❌ tuples can't change",
       note: 'قائمة ثابتة — استخدمها عندما يجب ألا يتغيّر الشكل: الإحداثيات، أزواج الإعدادات، البيانات للقراءة فقط.'},
      {title: 'المجموعات (Sets)', code: "s = {1, 2, 2, 3}   # {1, 2, 3} — duplicates dropped\ns.add(4)\n4 in s        # True\ns.remove(4)",
       note: 'كيس غير مرتب من العناصر الفريدة — مثالي لإزالة التكرار وفحص العضوية السريع.'},
      {title: 'عمليات المجموعات', code: "a = {1, 2, 3}\nb = {3, 4}\na | b       # {1, 2, 3, 4}  union\na & b       # {3}           intersection\na - b       # {1, 2}        difference\na ^ b       # {1, 2, 4}     symmetric",
       note: '| و& و- و^ تحوّل المجموعات إلى حساب في سطر واحد — قارن مجموعات دون حلقات متداخلة.'},
      {title: 'أي حاوية تختار؟', code: 'list    # ordered, editable, keeps order\ntuple   # ordered, read-only\nset     # unordered, unique, fast in\ndict    # key → value lookup',
       note: 'اختر حسب ما تحتاجه الشيفرة: الترتيب، أو التفرد، أو إيجاد الأشياء بالاسم.'},
    ],
  },
  {
    icon: '🗂️',
    title: 'القواميس',
    cards: [
      {title: 'الإنشاء والقراءة', code: "ages = {'ada': 36, 'bob': 41}\nages['ada']        # 36\nages.get('zoe')    # None (safe \"missing\")\nages.get('zoe', 0) # 0 (with default)",
       note: 'استخدام [key] مع مفتاح مفقود يرفع KeyError — فضّل .get() عندما لا تكون متأكدًا.'},
      {title: 'الكتابة', code: "ages['ada'] = 37\nages['zoe'] = 22\ndel ages['bob']",
       note: 'الإسناد يضيف أو يحدّث؛ بينما del يزيل مفتاحًا.'},
      {title: 'التكرار', code: "for k, v in ages.items():\n    print(k, v)",
       note: '.items() تعطي أزواج (مفتاح، قيمة)؛ بينما يعطي .keys() و .values() جانبًا واحدًا فقط.'},
    ],
  },
  {
    icon: '🔀',
    title: 'الشروط',
    cards: [
      {title: 'if / elif / else', code: 'if score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")',
       note: 'elif يتوقف بمجرد تحقق أحد الشروط — الترتيب مهم.'},
      {title: 'المقارنات', code: '==  !=  <  <=  >  >=',
       note: '== يفحص التساوي؛ بينما = يسند. تذكّر هذا ليصلّح معظم أخطاء «لماذا هو True» لدى المبتدئين.'},
      {title: 'العوامل المنطقية', code: 'a and b    # both truthy\na or b     # at least one\na and not b',
       note: 'and / or / not — كلمات عادية، وليست && و ! كما في اللغات الأخرى.'},
      {title: 'الصدق (Truthiness)', code: "if x:             # 'is x non-empty?'\n    print(x)\n# Falsy: 0, 0.0, '', [], {}, None\n# Everything else is truthy",
       note: '«if x:» هي الفحص الاصطلاحي «هل يوجد x؟» — الحاويات الفارغة و0 تفشل، وكل ما عدا ذلك ينجح.'},
      {title: 'الشرط الثلاثي في سطر واحد', code: "'pass' if score >= 50 else 'fail'",
       note: 'if/else مختصر يُرجع قيمة — رائع داخل f-strings والـ print().'},
    ],
  },
  {
    icon: '🔁',
    title: 'الحلقات التكرارية',
    cards: [
      {title: 'range', code: 'for i in range(3):   # 0, 1, 2\n    print(i)\nfor i in range(1, 4): # 1, 2, 3\n    print(i)',
       note: 'range يتوقف قبل الرقم الثاني — نفس قاعدة استبعاد النهاية كما في التقطيع.'},
      {title: 'enumerate / zip', code: "for i, item in enumerate(['a','b']):\n    print(i, item)\nfor x, y in zip([1,2],[3,4]):\n    print(x, y)",
       note: 'enumerate يضيف عدّادًا؛ بينما zip يزاوج تسلسلَين عنصرًا بعنصر.'},
      {title: 'break / continue', code: 'for n in range(10):\n    if n == 3:\n        break      # stop the loop\nfor n in range(10):\n    if n % 2:\n        continue   # skip this one\n    print(n)',
       note: 'break يخرج من الحلقة كليًا؛ بينما continue يقفز إلى التكرار التالي.'},
      {title: 'while', code: 'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1   # don\'t forget: while needs progress',
       note: 'while تتكرر حتى يصبح شرطها False — حلقة لا تحدّث شرطها لن تنتهي أبدًا.'},
      {title: 'else مع الحلقة (اختياري)', code: 'for n in nums:\n    if n == target:\n        break\nelse:\n    print("not found")',
       note: 'كتلة else تعمل فقط إذا انتهت الحلقة دون break — علمٌ مدمجٌ «هل وُجد؟».'},
    ],
  },
  {
    icon: '🛠️',
    title: 'الدوال',
    cards: [
      {title: 'التعريف والاستدعاء', code: 'def double(x):\n    return x * 2\n\ny = double(21)   # 42',
       note: 'نص def… يجب أن يكون مُزاحًا بمسافة بادئة. return تُعيد قيمة؛ وبدونه تحصل على None.'},
      {title: 'القيم الافتراضية والوسائط المفتاحية', code: 'def greet(name, exclaim=True):\n    s = f"Hello {name}"\n    return s + ("!" if exclaim else "")\n\ngreet("ada")        # Hello ada!\ngreet("ada", False) # Hello ada',
       note: 'المعلمات التي لها = تحصل على قيم افتراضية؛ ويمكن للمتصل تمريرها بالاسم (keyword).'},
      {title: 'إرجاع قيم متعددة', code: 'def minmax(nums):\n    return min(nums), max(nums)\n\nlo, hi = minmax([3, 1, 4])  # lo=1, hi=4',
       note: 'يمكن للدالة أن تُرجع صفًّا (tuple) ويفككه المتصل في عدة أسماء دفعة واحدة.'},
      {title: 'النطاق وprint مقابل return', code: 'x = 10            # global\n\ndef show(y):\n    x = 5         # local — different x!\n    print(x, y)   # side effect, returns None\n\nresult = show(1)  # result is None',
       note: 'print يعرض القيمة في الطرفية؛ أما return فتُرجِعها فعلًا. الإسناد داخل دالة يُظلّل المتغير العام.'},
      {title: 'لامدا (الصيغ القصيرة)', code: 'double = lambda x: x * 2\nsorted(nums, key=lambda n: -n)',
       note: 'استخدم lambdas للدوال المؤقتة المكوَّنة من سطر واحد وتُمرَّر إلى sort/max/map.'},
    ],
  },
  {
    icon: '🧰',
    title: 'الاستيعاب',
    cards: [
      {title: 'قائمة', code: '[n * 2 for n in nums]              # [2, 4, 6]\n[n for n in nums if n > 1]      # [2, 3]\n{n * 2 for n in nums}           # set',
       note: 'حلقة for داخل أقواس مربعة — الأسلوب الاصطلاحي لتحويل قائمة.'},
      {title: 'قاموس', code: "{n: n ** 2 for n in range(4)}   # {0: 0, 1: 1, 2: 4, 3: 9}",
       note: 'نفس الشكل، مع نقطتين بين المفتاح والقيمة.'},
    ],
  },
  {
    icon: '🗃️',
    title: 'الملفات وCSV',
    cards: [
      {title: 'قراءة ملف', code: 'text = open("file.txt").read()\nlines = text.splitlines()',
       note: 'أسهل طريقة للقراءة؛ استخدم with open(...) as f عندما تحتاج القراءة بالتدرج (streaming).'},
      {title: 'صفوف CSV', code: "import csv\nwith open('data.csv') as f:\n    rows = list(csv.reader(f))",
       note: 'rows[0] هو الترويسة (header)؛ وكل صف لاحق هو قائمة نصوص — حوّلها إلى أرقام قبل أي حساب.'},
    ],
  },
  {
    icon: '🐼',
    title: 'pandas (تحليل البيانات)',
    cards: [
      {title: 'التحميل والنظرة الأولى', code: "import pandas as pd\ndf = pd.read_csv('data.csv')\ndf.head()      # first 5 rows\ndf.describe()  # numeric summary",
       note: 'الصيغة القياسية — pd.read_csv هي طريقة بدء كل درس بيانات.'},
      {title: 'الأعمدة والصفوف', code: "df['name']          # one column\ndf[['a', 'b']]      # several\ndf.loc[0]           # first row\ndf[df['age'] > 30]  # filter rows",
       note: 'أقواس مربعة على اسم العمود؛ وأقنعة منطقية (boolean masks) للفلترة.'},
      {title: 'التجميع والإجمال', code: "df.groupby('city')['sales'].sum()\ndf.groupby('city').mean()",
       note: 'groupby + طريقة تلخيص واحدة هي محور قسم تحليل البيانات.'},
    ],
  },
  {
    icon: '🛟',
    title: 'معالجة الأخطاء',
    cards: [
      {title: 'اقرأ السطر الأخير', code: "TypeError: unsupported operand type(s) for +: 'int' and 'str'",
       note: 'السطر الأخير يسمّي الخطأ والقيم المخالفة — إنها الرسالة التي تخبرك بماذا تُصلح.'},
      {title: 'try / except', code: "try:\n    total = int(user_input) * 2\nexcept ValueError:\n    print('That was not a number')",
       note: 'التقط فقط الخطأ المحدد الذي تتوقعه؛ فالتقاط كل شيء يخفي أخطاءً حقيقية.'},
    ],
  },
];
