// Notebook companion links. Every lesson gets a real .ipynb generated by
// scripts/generate-notebooks.mjs into notebooks/<section>/<track>/<slug>.ipynb
// (committed to the repo), which cloud notebook runtimes open by URL.
// Translated lessons keep their notebooks under notebooks/<locale>/<section>/
// with a <track>-<slug>.ipynb name, so localized pages must pass locale.
const OWNER = 'abderrahim-lectures';
const REPO = 'python-data-analysis-course';
const BRANCH = 'main';

function repoPath(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return locale === 'en'
    ? `notebooks/${section}/${track}/${slug}.ipynb`
    : `notebooks/${locale}/${section}/${track}-${slug}.ipynb`;
}

export type Locale = 'en' | 'ar' | 'es' | 'fr';

/** GitHub blob view (used by Kaggle's GitHub import and direct link-out). */
export function notebookGitHubUrl(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return `https://github.com/${OWNER}/${REPO}/blob/${BRANCH}/${repoPath(locale, section, track, slug)}`;
}

/** Raw .ipynb bytes (nbviewer/Deepnote/Binder take a raw or web URL). */
export function notebookRawUrl(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return `https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/${repoPath(locale, section, track, slug)}`;
}

/** Google Colab opens notebooks from GitHub blob URLs. */
export function notebookColabUrl(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return `https://colab.research.google.com/github/${OWNER}/${REPO}/blob/${BRANCH}/${repoPath(locale, section, track, slug)}`;
}

/** nbviewer renders a notebook from a public URL. */
export function notebookNbviewerUrl(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return `https://nbviewer.org/urls/${notebookRawUrl(locale, section, track, slug).replace(/^https?:\/\//, '')}`;
}

/** Binder builds an ephemeral Jupyter env from the repo branch + filepath. */
export function notebookBinderUrl(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return `https://mybinder.org/v2/gh/${OWNER}/${REPO}/HEAD?filepath=${encodeURIComponent(repoPath(locale, section, track, slug))}`;
}

/** Deepnote imports a notebook from a public URL. */
export function notebookDeepnoteUrl(locale: Locale, section: string, track: 'normal' | 'hard', slug: string): string {
  return `https://deepnote.com/launch?url=${encodeURIComponent(notebookRawUrl(locale, section, track, slug))}`;
}

/**
 * "Open in Colab / Kaggle / others" buttons for a lesson. Kaggle has no
 * first-party open-by-URL — you import via GitHub (File → Import from GitHub)
 * or a browser extension — so its target is the GitHub blob view.
 */
export const NOTEBOOK_OPENERS = [
  {label: 'Colab', href: notebookColabUrl},
  {label: 'Kaggle', href: notebookGitHubUrl},
  {label: 'nbviewer', href: notebookNbviewerUrl},
  {label: 'Binder', href: notebookBinderUrl},
  {label: 'Deepnote', href: notebookDeepnoteUrl},
  {label: 'GitHub', href: notebookGitHubUrl},
] as const;