// Per-locale project slug maps, generated by scripts/generate-project-slugs.cjs
// from the localized `title` frontmatter. Keys are the canonical English slug
// (the content filename); values are the URL-safe localized slug for that
// locale. The EN route never uses a translated slug — it stays /projects/<english>.
import {PROJECT_SLUGS} from './projectSlugs.data';
import type {Locale} from './routeSegments';

/** URL slug for a project in the given locale. EN always stays the canonical
 *  English filename; unknown slugs (e.g. untranslated projects) fall back to
 *  the English slug so links never 404. */
export function localizedProjectSlug(locale: Locale, englishSlug: string): string {
  if (locale === 'en') return englishSlug;
  return PROJECT_SLUGS[locale][englishSlug] ?? englishSlug;
}