// @ts-check
import {createRequire} from 'node:module';
import fs from 'node:fs';
import {defineConfig} from 'astro/config';
import sitemap from '@astrojs/sitemap';
import {paraglideVitePlugin} from '@inlang/paraglide-js';
import {unified} from '@astrojs/markdown-remark';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import remarkAdmonitions from './src/lib/remark-admonitions.mjs';
import rehypeRunnablePython from './src/lib/rehype-runnable-python.mjs';
import rehypeSectionBlocks from './src/lib/rehype-section-blocks.mjs';
import rehypeDropLeadingH1 from './src/lib/rehype-drop-leading-h1.mjs';
import rehypeFixDocsLinks from './src/lib/rehype-fix-docs-links.mjs';

// Localized project slugs (EN filename -> localized URL slug per locale),
// generated by scripts/generate-project-slugs.cjs. Used by the sitemap filter
// to exclude the English-slug alias routes served for backward compatibility.
const projectSlugs = JSON.parse(
  fs.readFileSync(new URL('./src/lib/projectSlugs.data.json', import.meta.url), 'utf8'),
);

// The localized project page trees emit each project twice: once under its
// localized slug (canonical) and once under the English slug (alias so old
// links keep working). The sitemap must list only the canonical localized
// routes; alias pages are rendered but rel=canonical on them points at the
// localized URL, so listing both would send search engines to the same
// document twice. A slug whose localized form equals its English form has a
// single page and must NOT be filtered out.
const localizedProjectsWord = /** @type {Record<string,string>} */ ({ar: 'مشاريع', es: 'proyectos', fr: 'projets'});
const projectAliasPaths = new Set();
for (const locale of ['ar', 'es', 'fr']) {
  for (const [en, localized] of Object.entries(projectSlugs[locale] ?? {})) {
    if (localized !== en) {
      projectAliasPaths.add(`/${locale}/${localizedProjectsWord[locale]}/${en}`);
    }
  }
}

export default defineConfig({
  output: 'static',
  site: process.env.ASTRO_SITE ?? 'https://pyda-course.online/',
  base: process.env.ASTRO_BASE ?? '/',
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ar', 'es', 'fr'],
    routing: {prefixDefaultLocale: false},
  },
  vite: {
    plugins: [
      paraglideVitePlugin({
        project: './project.inlang',
        outdir: './src/paraglide',
        emitTsDeclarations: true,
        strategy: ['url', 'globalVariable', 'baseLocale'],
      }),
    ],
  },
  build: {inlineStylesheets: 'auto'},
  compressHTML: true,
  prefetch: {defaultStrategy: 'hover', prefetchAll: true},
  markdown: {
    shikiConfig: {theme: 'github-dark-default'},
    processor: unified({
      remarkPlugins: [remarkAdmonitions, remarkMath],
      rehypePlugins: [
        rehypeFixDocsLinks,
        rehypeDropLeadingH1,
        [rehypeKatex, {strict: false}],
        rehypeRunnablePython,
        rehypeSectionBlocks,
      ],
    }),
  },
  integrations: [
    // No sitemap-level x-default/hreflang here: the @astrojs/sitemap
    // integration cannot derive alternates across the translated URL
    // segments (تعلم vs learn etc.), and a self-referential x-default
    // is a wrong signal. The pages' <head> tags carry the correct
    // alternates (verified by tests/e2e/hreflang.mjs).
    sitemap({
      filter: (page) => {
        const url = new URL(page);
        return !projectAliasPaths.has(url.pathname);
      },
    }),
  ],
});