import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  python101Sidebar: [
    {type: 'autogenerated', dirName: 'python-101'},
  ],
  dataAnalysisSidebar: [
    {type: 'autogenerated', dirName: 'data-analysis'},
  ],
  bonusSidebar: [
    {type: 'autogenerated', dirName: 'bonus'},
  ],
};

export default sidebars;
